<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-28T22:02:04 IST" name="Default suite" finished-at="2022-07-28T22:02:29 IST" duration-ms="24759">
    <groups>
    </groups>
    <test started-at="2022-07-28T22:02:04 IST" name="Default test" finished-at="2022-07-28T22:02:29 IST" duration-ms="24759">
      <class name="TestRunner.loginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:04 IST" name="setUp" finished-at="2022-07-28T22:02:24 IST" duration-ms="19806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openTest()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:24 IST" name="openTest" finished-at="2022-07-28T22:02:25 IST" duration-ms="486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openTest -->
        <test-method signature="LoginButtonTest()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:25 IST" name="LoginButtonTest" finished-at="2022-07-28T22:02:25 IST" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginButtonTest -->
        <test-method signature="loginClick()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:25 IST" name="loginClick" finished-at="2022-07-28T22:02:29 IST" duration-ms="3815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginClick -->
        <test-method signature="verifyTitle()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:29 IST" name="verifyTitle" finished-at="2022-07-28T22:02:29 IST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Free CRM software for customer relationship management, sales, marketing campaigns and support.] but found [Cogmento CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Free CRM software for customer relationship management, sales, marketing campaigns and support.] but found [Cogmento CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestRunner.loginPageTest.verifyTitle(loginPageTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="closeTest()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:29 IST" name="closeTest" finished-at="2022-07-28T22:02:29 IST" duration-ms="413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TestRunner.loginPageTest@4803b726]" started-at="2022-07-28T22:02:29 IST" name="teardown" finished-at="2022-07-28T22:02:29 IST" duration-ms="223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestRunner.loginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
